spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
server:
  port: 8207

logging:
  file:
    name: logs/testprojectjava.log
    path: testprojectjava
  level:
    com.geppetto: info
  pattern:
    dateformat: "dd-MM-yyyy hh:mm:ss aa"



























